import eslint from "@eslint/js";

import type { Rules } from "../types";

export const javascriptRules = {
  ...eslint.configs.recommended.rules,
  "array-callback-return": [
    "error",
    {
      allowImplicit: true,
    },
  ],
  "arrow-body-style": ["error", "always"],
  "class-methods-use-this": "error",
  "consistent-return": "error",
  "curly": ["error", "all"],
  "default-case": "error",
  "default-case-last": "error",
  "no-await-in-loop": "error",
  "no-console": "warn",
  "no-implicit-coercion": "error",
  "no-implicit-globals": "error",
  "no-loop-func": "error",
  "no-new-wrappers": "error",
  "no-param-reassign": "error",
  "no-promise-executor-return": "error",
  "no-self-compare": "error",
  "no-template-curly-in-string": "error",
  "no-throw-literal": "error",
  "no-unmodified-loop-condition": "error",
  "no-unreachable-loop": "error",
  "no-use-before-define": [
    "error",
    {
      allowNamedExports: false,
      classes: false,
      functions: false,
      variables: true,
    },
  ],
  "no-useless-computed-key": "error",
  "no-useless-constructor": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-var": "error",
  "object-shorthand": "error",
  "prefer-arrow-callback": "error",
  "prefer-const": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  "radix": "error",
  "require-await": "error",
  "strict": ["error", "never"],
  "symbol-description": "error",
} satisfies Rules;
